# Generated by Django 5.0.2 on 2024-02-25 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTransacao',
            fields=[
                ('area_transacao_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID - Área Transação')),
                ('area_transacao_nome', models.CharField(max_length=100, unique=True, verbose_name='Área de Transação')),
                ('user_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário conectado')),
            ],
            options={
                'verbose_name': 'Área de transação',
                'verbose_name_plural': 'Áreas de transação',
                'ordering': ['area_transacao_nome'],
            },
        ),
        migrations.CreateModel(
            name='MetodoTransacao',
            fields=[
                ('metodo_transacao_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID - Método Transação')),
                ('metodo_transacao_nome', models.CharField(max_length=100, unique=True, verbose_name='Método de Transação')),
                ('metodo_transacao_tipo', models.CharField(choices=[('E', 'Eletrônico'), ('F', 'Físico')], max_length=1, verbose_name='Tipo de transação')),
                ('user_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário conectado')),
            ],
            options={
                'verbose_name': 'Método de transação',
                'verbose_name_plural': 'Métodos de transação',
                'ordering': ['metodo_transacao_nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('tipo_transacao_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID - Tipo Transação')),
                ('tipo_transacao_nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Transação')),
                ('user_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário conectado')),
            ],
            options={
                'verbose_name': 'Tipo de transação',
                'verbose_name_plural': 'Tipos de transação',
                'ordering': ['tipo_transacao_nome'],
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('saida_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID - Saída')),
                ('saida_data', models.DateField(verbose_name='Data')),
                ('saida_ds', models.CharField(max_length=100, verbose_name='Descrição')),
                ('saida_valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor')),
                ('saida_area', models.ForeignKey(default='Vários', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='saida_areatransacao', related_query_name='saida_areatransacao', to='transactions.areatransacao')),
                ('saida_metodo_transacao', models.ForeignKey(default='Dinheiro', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='saida_metodotransacao', related_query_name='saida_metodotransacao', to='transactions.metodotransacao')),
                ('user_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário conectado')),
                ('saida_tipo', models.ForeignKey(default='Fixa', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='saida_tipotransacao', related_query_name='saida_tipotransacao', to='transactions.tipotransacao')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
                'ordering': ['saida_data', 'saida_ds'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('entrada_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID - Entrada')),
                ('entrada_data', models.DateField(verbose_name='Data')),
                ('entrada_ds', models.CharField(max_length=100, verbose_name='Descrição')),
                ('entrada_valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor')),
                ('entrada_area', models.ForeignKey(default='Vários', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='entrada_areatransacao', related_query_name='entrada_areatransacao', to='transactions.areatransacao')),
                ('user_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário conectado')),
                ('entrada_metodo_transacao', models.ForeignKey(default='Dinheiro', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='entrada_metodotransacao', related_query_name='entrada_metodotransacao', to='transactions.metodotransacao')),
                ('entrada_tipo', models.ForeignKey(default='Fixa', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='entrada_tipotransacao', related_query_name='entrada_tipotransacao', to='transactions.tipotransacao')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['entrada_data', 'entrada_ds'],
            },
        ),
    ]
